# Generated by Django 4.0 on 2021-12-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=20)),
                ('rg', models.CharField(max_length=14)),
                ('cep', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('training_area', models.CharField(max_length=100)),
                ('position_at_school', models.CharField(choices=[('SD', 'SCHOOL DIRECTOR'), ('SC', 'SCHOOL COORDINATOR'), ('SJ', 'SCHOOL JANITOR'), ('SW', 'SCHOOL WATCHMAN'), ('T', 'TEACHER')], max_length=2)),
                ('ctps', models.CharField(max_length=25)),
                ('wage', models.DecimalField(decimal_places=2, max_digits=15)),
                ('hiring_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=20)),
                ('rg', models.CharField(max_length=14)),
                ('cep', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
