# Generated by Django 4.0 on 2021-12-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersregistration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolemployee',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
